name: PHP Unit Tests

on:
  push:
    branches:
      - develop
      - '[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "PHP ${{ matrix.php }}, WP ${{ matrix.multisite == true && 'Multisite' || 'Single Site' }} ${{ matrix.wp }}, PHPUnit ${{ matrix.phpunit }} (Test Suite: ${{ matrix.external-http == true && 'External HTTP' || 'Default' }})${{ matrix.coverage == true && '( with coverage)' || '' }}"
    runs-on: ubuntu-latest
    env:
      WP_CORE_DIR: /tmp/wordpress
    services:
      mysql:
        image: mariadb:latest
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_DATABASE: wordpress_test
          MARIADB_MYSQL_LOCALHOST_USER: 1
          MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        ports:
          - 3306
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        wp: ['latest']
        external-http: [false]
        install-pwa-plugin: [true]
        coverage: [false]
        multisite: [false]
        include:
          - php: '8.2'
            wp: 'trunk'
            phpunit: '9.6'
            experimental: true

          - php: '8.1'
            wp: 'trunk'
            phpunit: '9.6'
            experimental: true

          - php: '8.0'
            wp: 'trunk'
            phpunit: '9.3'
            multisite: true
            experimental: true

          - php: '8.0'
            wp: 'latest'
            phpunit: '9.3'
            coverage: true

          - php: '8.0'
            wp: 'latest'
            phpunit: '9.3'
            external-http: true

          - php: '7.4'
            wp: 'latest'
            phpunit: '9.3'
            multisite: true

          - php: '7.4'
            wp: 'latest'
            phpunit: '9.3'
            external-http: true

          - php: '7.4'
            wp: '5.3'
            phpunit: '7'

          - php: '7.4'
            wp: '5.3'
            phpunit: '7'
            external-http: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php-composer
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
          tools: 'composer,phpunit:${{ matrix.phpunit }}'

      - name: Setup NodeJS and NPM
        uses: ./.github/actions/setup-node-npm

      - name: Build plugin
        run: npm run build:js

      - name: Setup WordPress
        uses: ./.github/actions/wp-tests-setup
        with:
          unit-tests: true
          wp: ${{ matrix.wp }}
          install-pwa-plugin: ${{ matrix.install-pwa-plugin }}

      # Since locally installed PHPUnit classes are loaded into the classmap, running tests with globally
      # installed PHPUnit requires removing locally installed PHPUnit. Additionally, using the workflow matrix
      # makes it simple for us to maintain different PHPUnit versions for various PHP versions.
      - name: Remove locally installed PHPUnit
        run: |
          rm -rf vendor/phpunit
          composer dump-autoload -o

      - name: Run Single Site tests
        if: ${{ matrix.multisite == false }}
        run: |
            if [[ ${{ matrix.external-http == false }} == true && ${{ matrix.coverage == false }} == true ]]; then
              phpunit --verbose
            elif [[ ${{ matrix.external-http == true }} == true && ${{ matrix.coverage == false }} == true ]]; then
              phpunit --testsuite external-http --verbose
            elif [[ ${{ matrix.external-http == false }} == true && ${{ matrix.coverage == true }} == true ]]; then
              phpunit --verbose --coverage-clover ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp/build/logs/clover.xml
            elif [[ ${{ matrix.external-http == true }} == true && ${{ matrix.coverage == true }} == true ]]; then
              phpunit --testsuite external-http --verbose --coverage-clover ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp/build/logs/clover.xml
            fi
        working-directory: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib

      - name: Run multisite tests
        if: ${{ matrix.multisite == true }}
        run: |
          if [[ ${{ matrix.external-http == false }} == true && ${{ matrix.coverage == false }} == true ]]; then
            phpunit --verbose
          elif [[ ${{ matrix.external-http == true }} == true && ${{ matrix.coverage == false }} == true ]]; then
            phpunit --testsuite external-http --verbose
          elif [[ ${{ matrix.external-http == false }} == true && ${{ matrix.coverage == true }} == true ]]; then
            phpunit --verbose --coverage-clover ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp/build/logs/clover.xml
          elif [[ ${{ matrix.external-http == true }} == true && ${{ matrix.coverage == true }} == true ]]; then
            phpunit --testsuite external-http --verbose --coverage-clover ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp/build/logs/clover.xml
          fi
        working-directory: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_MULTISITE: 1

      - name: Upload code coverage report
        if: ${{ matrix.coverage == true && github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          file: ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/amp/build/logs/clover.xml
          flags: php,unit
          fail_ci_if_error: true
